services:
  webserver:
    # Use the official NGINX image from Docker Hub
    image: nginx:latest
    container_name: simple_website
    ports:
#      # Map port 8080 on your machine to port 80 in the container
      - "8555:80"
    volumes:
      # Mount the local html folder into the NGINX web root directory
      - ./html/index.html:/usr/share/nginx/html/index.html
    restart: unless-stopped
